# Generated by Django 4.2.3 on 2023-09-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_type', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('name', models.CharField(max_length=200)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('patient_appointment', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Another PCP', 'Another PCP'), ('Inactive-Insurance', 'Inactive-Insurance'), ('Follow Up', 'Patient with Follow up Appointment'), ('Blank-Patient', 'Blank-Patient'), ('N/A', 'N/A'), ('Referred', 'Referred'), ('Clear', 'Clear'), ('Deceased', 'Deceased'), ('Unreachable', 'Unreachable'), ('Terminated', 'Terminated')], null=True)),
                ('referred_by', models.CharField(blank=True, null=True)),
                ('last_appointment', models.DateField(blank=True, null=True)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('last_anthropometric_date', models.DateField(blank=True, null=True)),
                ('last_bmi', models.FloatField(blank=True, null=True)),
                ('last_bp_reading', models.CharField(blank=True, null=True)),
                ('reading_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bw_done', models.DateField(blank=True, null=True)),
                ('hb1ac_date', models.DateField(blank=True, null=True)),
                ('hb1ac', models.CharField(blank=True, choices=[('4-6', '4-6'), ('6-8', '6-8'), ('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('>14', '>14')], null=True)),
                ('fobt_date', models.DateField(blank=True, null=True)),
                ('colonoscopy_date', models.DateField(blank=True, null=True)),
                ('cologuard_date', models.DateField(blank=True, null=True)),
                ('pap_smear_date', models.DateField(blank=True, null=True)),
                ('mammogram_date', models.DateField(blank=True, null=True)),
                ('chronic_condition', models.CharField(blank=True, null=True)),
                ('enrolledin_PCM_CCM', models.CharField(blank=True, choices=[('PCM', 'Enrolled in PCM'), ('CCM', 'Enrolled in CCM'), ('not', 'Not Interested'), ('left', 'Left the Program'), ('not-eligible', 'Not Eligible')], null=True)),
                ('enrolledin_BHI', models.CharField(blank=True, choices=[('BHI', 'Enrolled in BHI'), ('not', 'Not Interested'), ('left', 'Left the Program'), ('not-eligible', 'Not Eligible')], null=True)),
                ('enrolledin_RPM', models.CharField(blank=True, choices=[('bp', 'BP Set'), ('sugar', 'Glucometer'), ('weight', 'Iscale'), ('not', 'Not Interested'), ('left', 'Left the Program'), ('not-eligible', 'Not Eligible')], null=True)),
                ('suboxone', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True)),
                ('medical_marijuana', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True)),
                ('other_controlled_med', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True)),
                ('last_uds_date', models.DateField(blank=True, null=True)),
                ('last_hospital_vist', models.DateField(blank=True, null=True)),
                ('annual_wellness_vist', models.DateField(blank=True, null=True)),
                ('transitional_care_vist', models.CharField(blank=True, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled')], null=True)),
                ('acp', models.DateField(blank=True, null=True)),
                ('med_reconcile_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant', to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_titan.insurance')),
                ('insurance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_titan.insurancetype')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_titan.provider')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'unique_together': {('name', 'date_of_birth')},
            },
        ),
    ]
