# Generated by Django 4.2.3 on 2023-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_titan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='enrolledin_BHI',
            field=models.CharField(blank=True, choices=[('Enrolled In BHI', 'Enrolled In BHI'), ('Not Eligible', 'Not Eligible'), ('left the program', 'left the program'), ('Not Interested', 'Not Interested')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enrolledin_PCM_CCM',
            field=models.CharField(blank=True, choices=[('Enrolled In PCM', 'Enrolled In PCM'), ('Enrolled In CCM', 'Enrolled In CCM'), ('Not Interested', 'Not Interested'), ('left the program', 'left the program'), ('Not Eligible', 'Not Eligible')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enrolledin_RPM',
            field=models.CharField(blank=True, choices=[('BP Set', 'BP Set'), ('Glucometer', 'Glucometer'), ('IScale', 'IScale'), ('Not Interested', 'Not Interested'), ('left the program', 'left the program'), ('Not Eligible', 'Not Eligible')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_marijuana',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_controlled_med',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('Another PCP', 'Another PCP'), ('Inactive Insurance', 'Inactive Insurance'), ('Patient with Follow Up appointment', 'Patient with Follow Up appointment'), ('Blank Patient', 'Blank Patient'), ('N/A', 'N/A'), ('Referred', 'Referred'), ('Clear', 'Clear'), ('Deceased', 'Deceased'), ('Unreachable', 'Unreachable'), ('Terminated', 'Terminated')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suboxone',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], null=True),
        ),
    ]
