# Generated by Django 4.2.3 on 2023-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_titan', '0002_alter_patient_enrolledin_bhi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='enrolledin_RPM',
            field=models.CharField(blank=True, choices=[('BP Set', 'BP Set'), ('Glucometer', 'Glucometer'), ('IScale', 'IScale'), ('Weight', 'Weight'), ('Not Interested', 'Not Interested'), ('left the program', 'left the program'), ('Not Eligible', 'Not Eligible')], null=True),
        ),
    ]
