# Generated by Django 4.2.3 on 2023-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_titan', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_bmi',
            field=models.CharField(blank=True, null=True),
        ),
    ]
