# Generated by Django 4.2.3 on 2023-10-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_titan', '0005_alter_patient_last_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
